"""Added the created_at and updated_at columns in the incidents table

Revision ID: 30a963de86d3
Revises: 336189bb5047
Create Date: 2023-12-07 14:18:58.890591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a963de86d3'
down_revision: Union[str, None] = '336189bb5047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('created_at', sa.String(length=50), nullable=False))
    op.add_column('incidents', sa.Column('updated_at', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'updated_at')
    op.drop_column('incidents', 'created_at')
    # ### end Alembic commands ###
