"""Made the product price be floats instead of Integers

Revision ID: 336189bb5047
Revises: b011cceb6e13
Create Date: 2023-12-07 14:15:48.444383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '336189bb5047'
down_revision: Union[str, None] = 'b011cceb6e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'product_price',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'product_price',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
