"""Deleted some unique constraints

Revision ID: 99335d5b2ea0
Revises: ae2a2036335d
Create Date: 2023-12-08 16:14:46.937585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99335d5b2ea0'
down_revision: Union[str, None] = 'ae2a2036335d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('employee_email', table_name='employees')
    op.drop_index('employee_phone_number', table_name='employees')
    op.drop_index('region_name', table_name='regions')
    op.drop_index('store_location', table_name='stores')
    op.drop_index('store_name', table_name='stores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('store_name', 'stores', ['store_name'], unique=False)
    op.create_index('store_location', 'stores', ['store_location'], unique=False)
    op.create_index('region_name', 'regions', ['region_name'], unique=False)
    op.create_index('employee_phone_number', 'employees', ['employee_phone_number'], unique=False)
    op.create_index('employee_email', 'employees', ['employee_email'], unique=False)
    # ### end Alembic commands ###
