"""Another fresh migration

Revision ID: ae2a2036335d
Revises: 
Create Date: 2023-12-08 15:36:46.193357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2a2036335d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('region_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('region_id'),
    sa.UniqueConstraint('region_name')
    )
    op.create_index(op.f('ix_regions_region_id'), 'regions', ['region_id'], unique=True)
    op.create_table('stores',
    sa.Column('store_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.String(length=50), nullable=False),
    sa.Column('store_location', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('store_id'),
    sa.UniqueConstraint('store_location'),
    sa.UniqueConstraint('store_name')
    )
    op.create_index(op.f('ix_stores_store_id'), 'stores', ['store_id'], unique=True)
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_name', sa.String(length=50), nullable=False),
    sa.Column('employee_email', sa.String(length=50), nullable=False),
    sa.Column('employee_phone_number', sa.String(length=50), nullable=False),
    sa.Column('employee_job_title', sa.String(length=50), nullable=False),
    sa.Column('employee_password', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('employee_email'),
    sa.UniqueConstraint('employee_phone_number')
    )
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    op.create_table('store_sections',
    sa.Column('store_section_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_section_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('store_section_id')
    )
    op.create_index(op.f('ix_store_sections_store_section_id'), 'store_sections', ['store_section_id'], unique=True)
    op.create_table('incidents',
    sa.Column('incident_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_description', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=50), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_quantity', sa.Integer(), nullable=False),
    sa.Column('product_price', sa.Float(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.Column('store_section_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['store_section_id'], ['store_sections.store_section_id'], ),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_index(op.f('ix_incidents_incident_id'), 'incidents', ['incident_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_incident_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_store_sections_store_section_id'), table_name='store_sections')
    op.drop_table('store_sections')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_stores_store_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_regions_region_id'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
