"""Updated some relationship function call items

Revision ID: b146bf295d61
Revises: bc3cdc1c3af5
Create Date: 2023-12-07 16:24:16.913961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b146bf295d61'
down_revision: Union[str, None] = 'bc3cdc1c3af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
